language: go
go_import_path: github.com/gallactic/gallactic
sudo: false

services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty
      go: 1.10.x
    - os: linux
      dist: trusty
      go: master
      
    - os: osx
      go: 1.10.x
    - os: osx
      go: master
      
    - os: windows
      go: 1.10.x
    - os: windows
      go: master

script: 
  - if [[ ( "$TRAVIS_OS_NAME" == "windows" ) ]]; then 
      mingw32-make && mingw32-make docker;
    else
      make && make docker;
    fi

before_install:
  # installing rust and cargo
  - curl -sSf rustup-install.sh https://sh.rustup.rs > rustup-install.sh
  - sh rustup-install.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"

deploy:
  provider: releases
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.10
